In [1]:
import numpy as np

In [47]:
A = np.random.randn(2,2)

In [48]:
A

array([[ 0.57206892, -1.69168475],
       [ 0.51533616, -1.55515564]])

In [62]:
dA = np.zeros((2,2))

In [66]:
for i in range(2):
    for j in range(2):
        if A[i,j] == np.amax(A):
            dA[i,j] = 1
        else:
            dA[i,j] = 0

In [67]:
dA

array([[1., 0.],
       [0., 0.]])

In [69]:
A >= np.amax(A)

array([[ True, False],
       [False, False]])

In [70]:
dA = A>= np.amax(A)

In [71]:
dA

array([[ True, False],
       [False, False]])

TypeError: only size-1 arrays can be converted to Python scalars